#include <hedley/hedley.h>

#if defined( NETWORKINGHELPER_IS_SHARED ) && defined( NETWORKINGHELPER_COMPILING )

#define NETWORKINGHELPER_API HEDLEY_PUBLIC

#elif defined( NETWORKINGHELPER_IS_SHARED )

#define NETWORKINGHELPER_API HEDLEY_IMPORT

#else

#define NETWORKINGHELPER_API

#endif
