#include <hedley/hedley.h>

#if defined( NETWORKINGHELPER_IS_SHARED ) && defined( NETWORKINGHELPER_COMPILING )

#define NETWORKINGHELPER_API_FUNCTIONS HEDLEY_PUBLIC
#define NETWORKINGHELPER_API_CLASSES HEDLEY_PUBLIC

#elif defined( NETWORKINGHELPER_IS_SHARED )

#define NETWORKINGHELPER_API_FUNCTIONS HEDLEY_IMPORT
#define NETWORKINGHELPER_API_CLASSES

#else

#define NETWORKINGHELPER_API_FUNCTIONS
#define NETWORKINGHELPER_API_CLASSES

#endif
